Relationships done
qAziz060708/Market pull request #3
Opened 2023-04-28 20:31 UTC by qAziz060708

2023-04-29 11:29 UTC, JmlKhon requested changes

2023-04-29 11:29 UTC, JmlKhon commented on Market/Market.DataAccess/Models/Categories.cs
remove empty space

2023-04-29 11:29 UTC, JmlKhon commented on Market/Market.DataAccess/Models/Customers.cs
> +        public List<Categories> categories { get; set; }
Prop names start with Capital letter

2023-04-29 11:29 UTC, JmlKhon commented on Market/Market.DataAccess/Models/Deliveries.cs
>         public int DeliveriesId { get; set; }
DeliveryId. NOT deliveriesId

2023-04-29 11:29 UTC, JmlKhon commented on Market/Market.DataAccess/Models/Deliveries.cs
>         public DateTime Date { get; set; }
aniqroq nomlash kerak! Date nima uchun? DeliveryDate ? CreatedDate

2023-04-29 11:29 UTC, JmlKhon commented on Market/Market.DataAccess/Models/Customers.cs
>      public class Customers
nima class nomi ko'plikda ? Customer qilamiz db kelishgandikku?

2023-04-29 11:29 UTC, JmlKhon commented on Market/Market.DataAccess/Models/Payment.cs
>          public DateTime Date { get; set; }
Change Date to proper name

2023-05-01 14:55 UTC, qAziz060708 commented on Market/Market.DataAccess/Models/Customers.cs
>      public class Customers
u ozi digramma shunaqa

2023-05-06 07:28 UTC, isfandiyoro5 requested changes

2023-05-06 07:28 UTC, isfandiyoro5 commented on Market/Market.DataAccess/Models/Category.cs
>          public int CategoryID { get; set; }
CategoryID emas CategoryId boladi

2023-05-06 07:28 UTC, isfandiyoro5 commented on Market/Market.DataAccess/Models/ShoppingOrder.cs
>          public DateTime Date { get; set; }
Shunda Date nima bolyabdi DeliveryDate yoki AcceptDate

2023-05-06 07:28 UTC, isfandiyoro5 commented on Market/Market.DataAccess/Models/Seller.cs
>          public string Name { get; set; }
Shu joyida FirstName bn LastName qilish kkmasmi

2023-05-06 07:28 UTC, isfandiyoro5 commented on Market/Market.DataAccess/Models/Customer.cs
>          public string Name { get; set; }
Shu joydayam FirstName LastName qilish kkmasmi

2023-05-09 07:18 UTC, merged